version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  # temporarily ignore updating this dependency until we can move to ruby 3+
  # see Gemfile for more info
  - dependency-name: html-proofer
    versions:
    - ">= 4.0.0"
