# this file is *NOT* reloaded when using 'bundle exec jekyll serve'. 

title: ariasemi

description: >- 
  My personal blog

author:
  name: Emilio Arias
  image: /assets/img/avatar.png

social:
  name: Emilio Arias
  links:
    - https://github.com/ariasemis
    - https://www.linkedin.com/in/ariasemi/

url: "https://blog.ariasemi.com/"

baseurl: "" # subpath

parent_url: "https://ariasemi.com/"

paginate: 5

permalink: /:slug

comments_api: https://emi-staticman.herokuapp.com/v2/entry/ariasemis/ariasemis.github.io/master/comments

repository: https://github.com/ariasemis/ariasemis.github.io

markdown: kramdown

collections:
  notes:
    output: true
    permalink: /:collection/:title

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/avatar.png
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "note"