# this file is *NOT* reloaded when using 'bundle exec jekyll serve'. 
# when changing this file, restart the server process.

# Site settings
title: ariasemis - blog
description: >- 
  My personal blog
baseurl: "" # subpath
url: "https://ariasemis.github.io/"

paginate: 5
# paginate_path: '/page:num'

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
