# this file is *NOT* reloaded when using 'bundle exec jekyll serve'. 

# Site settings
title: ariasemis - blog

description: >- 
  My personal blog

url: "https://ariasemis.github.io/"

baseurl: "" # subpath

paginate: 5

permalink: /:slug

comments_api: https://emi-staticman.herokuapp.com/v2/entry/ariasemis/ariasemis.github.io/feature%2Finit/comments

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate
