# this file is *NOT* reloaded when using 'bundle exec jekyll serve'. 

title: ariasemi - blog

description: >- 
  My personal blog

url: "https://blog.ariasemi.com/"

baseurl: "" # subpath

paginate: 5

permalink: /:slug

comments_api: https://emi-staticman.herokuapp.com/v2/entry/ariasemis/ariasemis.github.io/master/comments

repository: https://github.com/ariasemis/ariasemis.github.io

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/avatar.png
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"